"use client";

import React, { useState, useEffect } from "react";
import JSZip from "jszip";
import {
  X,
  FileCode,
  Download,
  Copy,
  Check,
  Package,
  Layers,
  Terminal,
  FileText,
  Boxes,
  Sparkles,
  ExternalLink,
  ShieldCheck,
  Code2,
} from "lucide-react";
import type { ComponentBundle, ComponentBundleFile } from "@codexel/shared";
import { CodeViewer } from "../CodeViewer";

interface ComponentExportModalProps {
  bundle: ComponentBundle | null;
  isOpen: boolean;
  onClose: () => void;
}

export function ComponentExportModal({
  bundle,
  isOpen,
  onClose,
}: ComponentExportModalProps) {
  const [selectedFileIndex, setSelectedFileIndex] = useState<number>(0);
  const [packageManager, setPackageManager] = useState<
    "pnpm" | "npm" | "yarn" | "bun"
  >("pnpm");
  const [copiedFile, setCopiedFile] = useState<boolean>(false);
  const [copiedCommand, setCopiedCommand] = useState<boolean>(false);
  const [copiedAll, setCopiedAll] = useState<boolean>(false);
  const [isZipping, setIsZipping] = useState<boolean>(false);

  // Reset selected file when bundle changes
  useEffect(() => {
    setSelectedFileIndex(0);
  }, [bundle?.componentId]);

  // Handle ESC key to close
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isOpen) {
        onClose();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen || !bundle) return null;

  const activeFile: ComponentBundleFile | undefined =
    bundle.files[selectedFileIndex] || bundle.files[0];

  const handleCopyCurrentFile = () => {
    if (!activeFile) return;
    navigator.clipboard.writeText(activeFile.content);
    setCopiedFile(true);
    setTimeout(() => setCopiedFile(false), 2000);
  };

  const handleCopyInstallCommand = () => {
    const cmd = bundle.installCommands[packageManager];
    navigator.clipboard.writeText(cmd);
    setCopiedCommand(true);
    setTimeout(() => setCopiedCommand(false), 2000);
  };

  const handleCopyAllFiles = () => {
    const combined = bundle.files
      .map(
        (f) =>
          `// ==========================================\n// File: ${f.relativePath}\n// ==========================================\n${f.content}\n`,
      )
      .join("\n\n");
    navigator.clipboard.writeText(combined);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  const handleDownloadZip = async () => {
    try {
      setIsZipping(true);
      const zip = new JSZip();

      // Add each file in its relative directory
      for (const file of bundle.files) {
        zip.file(file.relativePath, file.content);
      }

      // Add a README.md with installation and usage instructions
      const readmeContent = `# ${bundle.componentName} Component Bundle

Exported from **Codexel** repository intelligence.

## 📦 Required Dependencies

\`\`\`bash
${bundle.installCommands.pnpm}
\`\`\`

## 📁 Included Files (${bundle.summary.totalFiles} files, ${bundle.summary.totalLinesOfCode} lines of code)

${bundle.files
  .map(
    (f) =>
      `- \`${f.relativePath}\` (${f.fileType}, ${f.linesOfCode} LOC, ${f.sizeBytes} bytes)${
        f.isMainComponent ? " — **Root Component**" : ""
      }`,
  )
  .join("\n")}

---
*Generated by Codexel Architecture & Component Intelligence.*
`;
      zip.file("README.md", readmeContent);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${bundle.componentName.toLowerCase()}-bundle.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to generate zip bundle:", err);
    } finally {
      setIsZipping(false);
    }
  };

  const getBadgeStyle = (
    fileType: ComponentBundleFile["fileType"],
    isMain: boolean,
  ) => {
    if (isMain) {
      return "bg-primary/15 text-primary border-primary/30";
    }
    switch (fileType) {
      case "component":
        return "bg-sky-500/10 text-sky-500 border-sky-500/20";
      case "utility":
        return "bg-emerald-500/10 text-emerald-500 border-emerald-500/20";
      case "style":
        return "bg-pink-500/10 text-pink-500 border-pink-500/20";
      case "config":
        return "bg-amber-500/10 text-amber-500 border-amber-500/20";
      default:
        return "bg-surface-secondary text-foreground-muted border-border";
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/70 backdrop-blur-sm animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="relative w-full max-w-5xl h-[90vh] max-h-[850px] flex flex-col bg-surface border border-border rounded-xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-4 sm:px-6 border-b border-border bg-surface-secondary/50 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 truncate">
            <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
              <Boxes className="w-5 h-5" />
            </div>
            <div className="truncate">
              <div className="flex items-center gap-2">
                <h2 className="text-base sm:text-lg font-bold font-mono text-foreground tracking-tight">
                  {bundle.componentName}
                </h2>
                <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20">
                  Dependency Closure
                </span>
              </div>
              <p className="text-xs font-mono text-foreground-muted truncate">
                {bundle.summary.totalFiles} files •{" "}
                {bundle.summary.totalLinesOfCode} lines of code •{" "}
                {bundle.externalPackages.length} npm packages
              </p>
            </div>
          </div>

          {/* Quick Action Buttons */}
          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={handleCopyAllFiles}
              className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono rounded-lg border border-border bg-surface hover:bg-surface-secondary text-foreground transition-colors"
              title="Copy all bundle files as a single markdown snippet"
            >
              {copiedAll ? (
                <>
                  <Check className="w-3.5 h-3.5 text-semantic-green" />
                  <span className="text-semantic-green font-semibold">
                    Copied All
                  </span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy All</span>
                </>
              )}
            </button>

            <button
              type="button"
              onClick={handleDownloadZip}
              disabled={isZipping}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-mono font-semibold rounded-lg bg-primary hover:bg-primary/90 text-white shadow-subtle transition-colors disabled:opacity-50"
            >
              <Download className="w-3.5 h-3.5" />
              <span>{isZipping ? "Zipping..." : "Download ZIP"}</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-surface-secondary text-foreground-muted hover:text-foreground transition-colors"
              title="Close modal (Esc)"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Sub-Header: Package Manager Installation Commands */}
        <div className="px-4 sm:px-6 py-2.5 bg-surface-secondary/30 border-b border-border flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
          <div className="flex items-center gap-2 overflow-x-auto text-xs font-mono">
            <span className="text-foreground-muted text-[11px] font-semibold flex items-center gap-1 shrink-0">
              <Terminal className="w-3.5 h-3.5 text-primary" /> Install:
            </span>
            {(["pnpm", "npm", "yarn", "bun"] as const).map((pm) => (
              <button
                key={pm}
                type="button"
                onClick={() => setPackageManager(pm)}
                className={`px-2 py-0.5 rounded transition-colors text-[11px] ${
                  packageManager === pm
                    ? "bg-primary text-white font-bold"
                    : "text-foreground-muted hover:text-foreground hover:bg-surface"
                }`}
              >
                {pm}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2 bg-surface border border-border px-2.5 py-1 rounded-md text-xs font-mono text-foreground-secondary flex-1 sm:max-w-md">
            <span className="truncate select-all text-[11px] flex-1">
              {bundle.installCommands[packageManager]}
            </span>
            <button
              type="button"
              onClick={handleCopyInstallCommand}
              className="p-1 hover:bg-surface-secondary rounded text-foreground-muted hover:text-foreground transition-colors shrink-0"
              title="Copy installation command"
            >
              {copiedCommand ? (
                <Check className="w-3.5 h-3.5 text-semantic-green" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
            </button>
          </div>
        </div>

        {/* Main Body: Two-Column Workspace */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          {/* Left Column: Bundled Files Tree */}
          <div className="w-full md:w-80 border-b md:border-b-0 md:border-r border-border bg-surface flex flex-col overflow-hidden shrink-0">
            <div className="p-3 border-b border-border bg-surface-secondary/20 flex items-center justify-between text-xs font-mono">
              <span className="font-bold text-foreground uppercase tracking-wider text-[10px]">
                Bundled Files ({bundle.files.length})
              </span>
              <span className="text-foreground-muted text-[10px]">
                {Math.round((bundle.summary.totalSizeBytes / 1024) * 10) / 10}{" "}
                KB
              </span>
            </div>

            <div className="flex-1 overflow-y-auto p-2 space-y-1">
              {bundle.files.map((file, idx) => {
                const isSelected = idx === selectedFileIndex;
                return (
                  <button
                    key={file.filePath}
                    type="button"
                    onClick={() => setSelectedFileIndex(idx)}
                    className={`w-full text-left p-2.5 rounded-lg border text-xs font-mono transition-colors flex items-start justify-between gap-2 ${
                      isSelected
                        ? "bg-primary/10 border-primary/40 text-foreground shadow-xs"
                        : "bg-surface hover:bg-surface-secondary/60 border-transparent text-foreground-secondary"
                    }`}
                  >
                    <div className="flex items-start gap-2 truncate">
                      <FileCode
                        className={`w-4 h-4 mt-0.5 shrink-0 ${
                          isSelected ? "text-primary" : "text-foreground-muted"
                        }`}
                      />
                      <div className="truncate">
                        <div className="font-semibold truncate text-foreground flex items-center gap-1.5">
                          <span>{file.fileName}</span>
                          {file.isMainComponent && (
                            <span className="text-[9px] px-1.5 py-0.2 rounded bg-primary text-white font-bold uppercase">
                              Root
                            </span>
                          )}
                        </div>
                        <div className="text-[10px] text-foreground-muted truncate">
                          {file.relativePath}
                        </div>
                      </div>
                    </div>

                    <div className="flex flex-col items-end gap-1 shrink-0">
                      <span
                        className={`text-[9px] px-1.5 py-0.5 rounded border uppercase font-semibold ${getBadgeStyle(
                          file.fileType,
                          file.isMainComponent,
                        )}`}
                      >
                        {file.fileType}
                      </span>
                      <span className="text-[9px] text-foreground-muted font-mono">
                        {file.linesOfCode}L
                      </span>
                    </div>
                  </button>
                );
              })}
            </div>

            {/* External Dependencies Summary in Left Sidebar */}
            <div className="p-3 border-t border-border bg-surface-secondary/30 space-y-2">
              <div className="flex items-center justify-between text-[10px] font-mono uppercase font-bold text-foreground-muted">
                <span>
                  External Packages ({bundle.externalPackages.length})
                </span>
              </div>
              {bundle.externalPackages.length === 0 ? (
                <p className="text-[10px] font-mono text-foreground-muted">
                  Zero external npm dependencies.
                </p>
              ) : (
                <div className="flex flex-wrap gap-1 max-h-24 overflow-y-auto">
                  {bundle.externalPackages.map((pkg) => (
                    <span
                      key={pkg.name}
                      className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20 text-[10px] font-mono"
                      title={
                        pkg.version ? `Version: ${pkg.version}` : undefined
                      }
                    >
                      <Package className="w-2.5 h-2.5" />
                      <span>{pkg.name}</span>
                      {pkg.version && (
                        <span className="opacity-60 text-[9px]">
                          {pkg.version}
                        </span>
                      )}
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Right Column: Code Viewer */}
          <div className="flex-1 flex flex-col overflow-hidden bg-surface">
            {activeFile ? (
              <>
                <div className="p-3 px-4 border-b border-border bg-surface-secondary/40 flex items-center justify-between gap-3 text-xs font-mono">
                  <div className="flex items-center gap-2 truncate">
                    <FileCode className="w-4 h-4 text-primary shrink-0" />
                    <span className="font-bold text-foreground truncate">
                      {activeFile.relativePath}
                    </span>
                    <span className="text-[10px] text-foreground-muted shrink-0">
                      ({activeFile.linesOfCode} lines, {activeFile.sizeBytes}{" "}
                      bytes)
                    </span>
                  </div>

                  <button
                    type="button"
                    onClick={handleCopyCurrentFile}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-mono rounded-md border border-border bg-surface hover:bg-surface-secondary text-foreground transition-colors shrink-0"
                  >
                    {copiedFile ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-semantic-green" />
                        <span className="text-semantic-green font-semibold">
                          Copied
                        </span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy File</span>
                      </>
                    )}
                  </button>
                </div>

                <div className="flex-1 overflow-hidden p-3 bg-surface">
                  <CodeViewer
                    code={activeFile.content}
                    language={
                      activeFile.fileName.endsWith(".tsx") ||
                      activeFile.fileName.endsWith(".jsx")
                        ? "tsx"
                        : activeFile.fileName.endsWith(".css")
                          ? "css"
                          : activeFile.fileName.endsWith(".json")
                            ? "json"
                            : "typescript"
                    }
                    filePath={activeFile.relativePath}
                    className="h-full border border-border rounded-lg"
                  />
                </div>
              </>
            ) : (
              <div className="flex-1 flex items-center justify-center p-8 text-center text-foreground-muted font-mono text-xs">
                Select a file from the left sidebar to inspect its code.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
