import type { RepositoryModel } from "@codexel/shared";

export interface ExportSectionsConfig {
  overview: boolean;
  aiSummary: boolean;
  architecture: boolean;
  components: boolean;
  designSystem: boolean;
  routes: boolean;
  dependencyGraph: boolean;
}

export const DEFAULT_EXPORT_SECTIONS: ExportSectionsConfig = {
  overview: true,
  aiSummary: true,
  architecture: true,
  components: true,
  designSystem: true,
  routes: true,
  dependencyGraph: false,
};

export function generateRepositoryMarkdown(
  model: RepositoryModel,
  config: ExportSectionsConfig,
): string {
  const {
    metadata,
    technologyStack,
    fileSystem,
    architecture,
    components,
    designSystem,
    routes,
    dependencyGraph,
  } = model;

  const parts: string[] = [];

  // Document Title & Metadata Header
  parts.push(
    `# Architectural Specification & Design System: ${metadata.owner}/${metadata.name}\n`,
  );
  parts.push(
    `> Generated by **Codexel** — Deterministic Static Architecture Engine on ${new Date(
      metadata.analyzedAt || Date.now(),
    ).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}\n`,
  );

  // 1. Overview & Tech Stack
  if (config.overview) {
    parts.push(`## 1. Repository Overview & Tech Stack\n`);
    parts.push(
      `| Attribute | Value |`,
      `| :--- | :--- |`,
      `| **Repository** | [${metadata.owner}/${metadata.name}](${metadata.url}) |`,
      `| **Default Branch** | \`${metadata.defaultBranch}\` |`,
      `| **Commit SHA** | \`${metadata.commitSha}\` |`,
      `| **Primary Language** | **${technologyStack.primaryLanguage}** |`,
      `| **Total Source Files** | ${fileSystem.totalFiles} files |`,
      `| **Total Lines of Code** | ${fileSystem.totalLinesOfCode.toLocaleString()} loc |`,
      `| **Components Discovered** | ${components.totalComponents} |`,
      `| **Architecture Layers** | ${architecture.layers.length} |`,
      `\n`,
    );

    // Languages Table
    if (technologyStack.languages.length > 0) {
      parts.push(`### Languages Breakdown\n`);
      parts.push(`| Language | Percentage | File Count |`);
      parts.push(`| :--- | :--- | :--- |`);
      for (const lang of technologyStack.languages) {
        parts.push(
          `| ${lang.name} | ${lang.percentage}% | ${lang.fileCount} files |`,
        );
      }
      parts.push(`\n`);
    }

    // Frameworks & Libraries
    const frameworks = [
      ...technologyStack.frameworks,
      ...technologyStack.styling,
      ...technologyStack.database,
      ...technologyStack.uiLibraries,
    ];
    if (frameworks.length > 0) {
      parts.push(`### Detected Frameworks & Infrastructure\n`);
      parts.push(`| Category | Package / Technology | Matched Evidence |`);
      parts.push(`| :--- | :--- | :--- |`);
      for (const t of frameworks) {
        parts.push(
          `| \`${t.category}\` | **${t.name}**${t.version ? ` (\`${t.version}\`)` : ""} | ${t.evidence.description || t.evidence.filePath} |`,
        );
      }
      parts.push(`\n`);
    }
  }

  // 2. AI Architecture Overview / Summary
  if (config.aiSummary) {
    parts.push(`## 2. Architectural Synthesis & System Overview\n`);
    parts.push(
      `This repository is architectured around a **${technologyStack.primaryLanguage}** stack utilizing `,
    );
    if (technologyStack.frameworks.length > 0) {
      parts.push(
        `**${technologyStack.frameworks.map((f) => f.name).join(", ")}** `,
      );
    }
    parts.push(
      `with a total of **${fileSystem.totalFiles}** tracked files across **${architecture.layers.length}** distinct functional layers.\n\n`,
    );

    // Architectural Layer Distribution
    parts.push(`### Structural Layer Roles\n`);
    for (const layer of architecture.layers) {
      parts.push(
        `- **${layer.name}** (\`${layer.role}\`): ${layer.fileCount} files — *${layer.evidence}* (${Math.round(layer.confidenceScore * 100)}% verified)`,
      );
    }
    parts.push(`\n`);

    // Key architectural principles
    parts.push(
      `> [!NOTE]\n> All boundaries between modules are mapped deterministically through AST static import resolution.\n\n`,
    );
  }

  // 3. Architecture Layers, Boundaries & Mermaid Graph
  if (config.architecture) {
    parts.push(`## 3. Architecture Layers & Boundary Conventions\n`);

    // Mermaid Diagram
    parts.push(`### Architecture DAG (Mermaid)\n`);
    parts.push(`\`\`\`mermaid`);
    parts.push(`graph TD`);
    for (const layer of architecture.layers) {
      const sanitizedId = layer.id.replace(/[^a-zA-Z0-9_]/g, "_");
      parts.push(`  ${sanitizedId}["${layer.name} (${layer.role})"]`);
    }
    for (const boundary of architecture.boundaries) {
      const src = boundary.sourceLayerId.replace(/[^a-zA-Z0-9_]/g, "_");
      const tgt = boundary.targetLayerId.replace(/[^a-zA-Z0-9_]/g, "_");
      const arrow = boundary.isAllowedByConvention ? "-->" : "-.->";
      parts.push(`  ${src} ${arrow}|${boundary.importCount} refs| ${tgt}`);
    }
    parts.push(`\`\`\`\n`);

    // Layers Table
    parts.push(`### Defined Architectural Layers\n`);
    parts.push(
      `| Layer Name | Role | File Count | Verified Fact | Confidence | Directory Paths |`,
    );
    parts.push(`| :--- | :--- | :--- | :--- | :--- | :--- |`);
    for (const layer of architecture.layers) {
      const paths = layer.directoryPaths.map((p) => `\`${p}\``).join(", ");
      parts.push(
        `| **${layer.name}** | \`${layer.role}\` | ${layer.fileCount} | ${layer.isConfirmedFact ? "Yes" : "Inferred"} | ${Math.round(layer.confidenceScore * 100)}% | ${paths || "root"} |`,
      );
    }
    parts.push(`\n`);

    // Boundaries Table
    if (architecture.boundaries.length > 0) {
      parts.push(`### Module Boundary Rules & Import Compliance\n`);
      parts.push(
        `| Source Layer | Target Layer | Import References | Allowed by Convention |`,
      );
      parts.push(`| :--- | :--- | :--- | :--- |`);
      for (const b of architecture.boundaries) {
        parts.push(
          `| \`${b.sourceLayerId}\` | \`${b.targetLayerId}\` | ${b.importCount} refs | ${b.isAllowedByConvention ? "Allowed" : "Warning (Cross-Layer Violation)"} |`,
        );
      }
      parts.push(`\n`);
    }
  }

  // 4. Component Inventory & Props
  if (config.components) {
    parts.push(
      `## 4. Component Inventory (${components.totalComponents} Discovered)\n`,
    );

    parts.push(
      `| Component Name | Category | File Path | Props Count | Dependencies |`,
    );
    parts.push(`| :--- | :--- | :--- | :--- | :--- |`);
    for (const comp of components.components) {
      const depCount =
        comp.localDependencies.length + comp.externalPackageDependencies.length;
      parts.push(
        `| **${comp.name}** | \`${comp.category}\` | \`${comp.filePath}\` | ${comp.props.length} | ${depCount} deps |`,
      );
    }
    parts.push(`\n`);

    // Detailed Props Specifications for components with props
    const componentsWithProps = components.components.filter(
      (c) => c.props.length > 0,
    );
    if (componentsWithProps.length > 0) {
      parts.push(`### Component Prop Specifications\n`);
      for (const comp of componentsWithProps.slice(0, 30)) {
        parts.push(`#### \`<${comp.name} />\` (\`${comp.filePath}\`)\n`);
        parts.push(`| Prop Name | Type | Required | Default Value |`);
        parts.push(`| :--- | :--- | :--- | :--- |`);
        for (const prop of comp.props) {
          parts.push(
            `| \`${prop.name}\` | \`${prop.type}\` | ${prop.isRequired ? "**Yes**" : "No"} | ${prop.defaultValue ? `\`${prop.defaultValue}\`` : "—"} |`,
          );
        }
        parts.push(`\n`);
      }
      if (componentsWithProps.length > 30) {
        parts.push(
          `*...and ${componentsWithProps.length - 30} additional components with defined prop signatures.*\n\n`,
        );
      }
    }
  }

  // 5. Design System & Color Scheme
  if (config.designSystem) {
    parts.push(`## 5. Design System & Visual Specification\n`);

    // Extracted Color Palette
    if (designSystem.colorPalette.length > 0) {
      parts.push(
        `### Extracted Color Palette (${designSystem.colorPalette.length} Tokens)\n`,
      );
      parts.push(`| Token / Name | Value / Hex | Source |`);
      parts.push(`| :--- | :--- | :--- |`);
      for (const color of designSystem.colorPalette) {
        parts.push(
          `| \`${color.name}\` | \`${color.value}\` | \`${color.source}\` |`,
        );
      }
      parts.push(`\n`);
    }

    // Detected CSS Variables
    const cssVars = Object.entries(designSystem.detectedCssVariables);
    if (cssVars.length > 0) {
      parts.push(`### Detected CSS Variables (${cssVars.length})\n`);
      parts.push(`| Variable | Default Value |`);
      parts.push(`| :--- | :--- |`);
      for (const [key, val] of cssVars.slice(0, 40)) {
        parts.push(`| \`${key}\` | \`${val}\` |`);
      }
      parts.push(`\n`);
    }

    // Spacing & Border Radii
    if (
      designSystem.spacing.length > 0 ||
      designSystem.borderRadii.length > 0
    ) {
      parts.push(`### Metrics & Radii Tokens\n`);
      if (designSystem.spacing.length > 0) {
        parts.push(
          `- **Spacing Scale**: ${designSystem.spacing.map((s) => `\`${s}\``).join(", ")}`,
        );
      }
      if (designSystem.borderRadii.length > 0) {
        parts.push(
          `- **Border Radii**: ${designSystem.borderRadii.map((r) => `\`${r}\``).join(", ")}`,
        );
      }
      parts.push(`\n`);
    }

    // Top Tailwind Utilities
    if (designSystem.topTailwindClasses.length > 0) {
      parts.push(`### Top Tailwind Utility Classes\n`);
      parts.push(`| Utility Class | Frequency Count |`);
      parts.push(`| :--- | :--- |`);
      for (const item of designSystem.topTailwindClasses.slice(0, 25)) {
        parts.push(`| \`${item.className}\` | ${item.count} occurrences |`);
      }
      parts.push(`\n`);
    }
  }

  // 6. Application Routes & API Endpoints
  if (config.routes && routes.routes.length > 0) {
    parts.push(
      `## 6. Application Routes & API Endpoints (${routes.routes.length} Routes)\n`,
    );
    parts.push(`Router Type: **\`${routes.routerType}\`**\n`);
    parts.push(`| Route Path | Kind | File Location | HTTP Methods |`);
    parts.push(`| :--- | :--- | :--- | :--- |`);
    for (const r of routes.routes) {
      const methods = r.httpMethods?.join(", ") || "GET";
      parts.push(
        `| \`${r.routePath}\` | \`${r.kind}\` | \`${r.filePath}\` | \`${methods}\` |`,
      );
    }
    parts.push(`\n`);
  }

  // 7. Module Dependency Graph
  if (config.dependencyGraph && dependencyGraph.nodes.length > 0) {
    parts.push(
      `## 7. Dependency Graph & Module Hubs (${dependencyGraph.nodes.length} Nodes)\n`,
    );

    // Top In-Degree Hubs
    const sortedByInDegree = [...dependencyGraph.nodes]
      .filter((n) => (n.data.inDegree || 0) > 0)
      .sort((a, b) => (b.data.inDegree || 0) - (a.data.inDegree || 0))
      .slice(0, 15);

    if (sortedByInDegree.length > 0) {
      parts.push(`### Most Imported Core Modules (Top In-Degree)\n`);
      parts.push(`| Module File | In-Degree (Dependents) | Out-Degree | LOC |`);
      parts.push(`| :--- | :--- | :--- | :--- |`);
      for (const node of sortedByInDegree) {
        parts.push(
          `| \`${node.data.filePath || node.id}\` | **${node.data.inDegree}** | ${node.data.outDegree || 0} | ${node.data.linesOfCode || "—"} |`,
        );
      }
      parts.push(`\n`);
    }
  }

  // Document Footer
  parts.push(`---\n`);
  parts.push(
    `*Generated with [Codexel](https://github.com/Abhaynegi1/Codexel) — Visual Developer Workspace.*`,
  );

  return parts.join("\n");
}
